# Generated by Django 2.0.2 on 2018-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('car_1', models.FloatField()),
                ('car_2', models.FloatField()),
                ('car_3', models.FloatField()),
                ('car_4', models.FloatField()),
                ('car_5', models.FloatField()),
                ('car_6', models.FloatField()),
                ('car_7', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('car_1', models.FloatField()),
                ('car_2', models.FloatField()),
                ('car_3', models.FloatField()),
                ('car_4', models.FloatField()),
                ('car_5', models.FloatField()),
            ],
        ),
    ]
