# Generated by Django 2.0.2 on 2018-05-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneditem',
            name='car_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banneditem',
            name='car_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banneditem',
            name='car_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banneditem',
            name='car_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banneditem',
            name='car_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banneditem',
            name='car_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banneditem',
            name='car_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='car_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='car_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='car_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='car_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='car_5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
