# Generated by Django 2.0.2 on 2018-05-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20180524_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banneditem',
            old_name='car_1',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='banneditem',
            old_name='car_2',
            new_name='demanda',
        ),
        migrations.RenameField(
            model_name='banneditem',
            old_name='car_3',
            new_name='ganancia',
        ),
        migrations.RenameField(
            model_name='banneditem',
            old_name='car_4',
            new_name='tiempo_fuera',
        ),
        migrations.RenameField(
            model_name='banneditem',
            old_name='car_5',
            new_name='tiempo_mercado',
        ),
        migrations.RenameField(
            model_name='banneditem',
            old_name='car_6',
            new_name='valor_independiente',
        ),
        migrations.RenameField(
            model_name='banneditem',
            old_name='car_7',
            new_name='valor_mercado',
        ),
        migrations.RenameField(
            model_name='liveitem',
            old_name='car_1',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='liveitem',
            old_name='car_2',
            new_name='demanda',
        ),
        migrations.RenameField(
            model_name='liveitem',
            old_name='car_3',
            new_name='ganancia',
        ),
        migrations.RenameField(
            model_name='liveitem',
            old_name='car_4',
            new_name='tiempo_mercado',
        ),
        migrations.RenameField(
            model_name='liveitem',
            old_name='car_5',
            new_name='valor_mercado',
        ),
    ]
