# Generated by Django 2.0.2 on 2018-05-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20180524_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banneditem',
            old_name='valor_independiente',
            new_name='valor_individual',
        ),
    ]
